db.stores.insert({storeNumber: "R104",storeName: "Bridgewater",storeEnabled: true,storeState: "New Jersey",sellEdition: false,storeCity: "Bridgewater"})
db.stores.insert({storeNumber: "R093",storeName: "Danbury Fair Mall",storeEnabled: true,storeState: "Connecticut",sellEdition: false,storeCity: "Danbury"})
db.stores.insert({storeNumber: "R095",storeName: "Fifth Avenue",storeEnabled: true,storeState: "New York",sellEdition: true,storeCity: "New York"})
db.stores.insert({storeNumber: "R138",storeName: "Freehold Raceway Mall",storeEnabled: true,storeState: "New Jersey",sellEdition: false,storeCity: "Freehold"})
db.stores.insert({storeNumber: "R117",storeName: "Garden State Plaza",storeEnabled: true,storeState: "New Jersey",sellEdition: false,storeCity: "Paramus"})
db.stores.insert({storeNumber: "R415",storeName: "Grand Central",storeEnabled: true,storeState: "New York",sellEdition: false,storeCity: "New York"})
db.stores.insert({storeNumber: "R282",storeName: "Greenwich Avenue",storeEnabled: true,storeState: "Connecticut",sellEdition: false,storeCity: "Greenwich"})
db.stores.insert({storeNumber: "R327",storeName: "Manhasset",storeEnabled: true,storeState: "New York",sellEdition: false,storeCity: "Manhasset"})
db.stores.insert({storeNumber: "R067",storeName: "Menlo Park",storeEnabled: true,storeState: "New Jersey",sellEdition: false,storeCity: "Edison"})
db.stores.insert({storeNumber: "R046",storeName: "Nanuet",storeEnabled: true,storeState: "New York",sellEdition: false,storeCity: "Nanuet"})
db.stores.insert({storeNumber: "R446",storeName: "New Haven",storeEnabled: true,storeState: "Connecticut",sellEdition: false,storeCity: "New Haven"})
db.stores.insert({storeNumber: "R549",storeName: "Quaker Bridge",storeEnabled: true,storeState: "New Jersey",sellEdition: false,storeCity: "Lawrence Township"})
db.stores.insert({storeNumber: "R612",storeName: "Queens Center",storeEnabled: true,storeState: "New York",sellEdition: false,storeCity: "Elmhurst"})
db.stores.insert({storeNumber: "R261",storeName: "Ridge Hill",storeEnabled: true,storeState: "New York",sellEdition: false,storeCity: "Yonkers"})
db.stores.insert({storeNumber: "R103",storeName: "Rockaway",storeEnabled: true,storeState: "New Jersey",sellEdition: false,storeCity: "Rockaway"})
db.stores.insert({storeNumber: "R060",storeName: "Roosevelt Field",storeEnabled: true,storeState: "New York",sellEdition: false,storeCity: "Garden City"})
db.stores.insert({storeNumber: "R043",storeName: "Short Hills",storeEnabled: true,storeState: "New Jersey",sellEdition: false,storeCity: "Short Hills"})
db.stores.insert({storeNumber: "R139",storeName: "Smith Haven",storeEnabled: true,storeState: "New York",sellEdition: false,storeCity: "Lake Grove"})
db.stores.insert({storeNumber: "R032",storeName: "SoHo",storeEnabled: true,storeState: "New York",sellEdition: false,storeCity: "New York"})
db.stores.insert({storeNumber: "R202",storeName: "Stamford",storeEnabled: true,storeState: "Connecticut",sellEdition: false,storeCity: "Stamford"})
db.stores.insert({storeNumber: "R152",storeName: "Staten Island",storeEnabled: true,storeState: "New York",sellEdition: false,storeCity: "Staten Island"})
db.stores.insert({storeNumber: "R061",storeName: "The Westchester",storeEnabled: true,storeState: "New York",sellEdition: false,storeCity: "White Plains"})
db.stores.insert({storeNumber: "R013",storeName: "Tice's Corner",storeEnabled: true,storeState: "New Jersey",sellEdition: false,storeCity: "Woodcliff Lake"})
db.stores.insert({storeNumber: "R629",storeName: "Trumbull",storeEnabled: true,storeState: "Connecticut",sellEdition: false,storeCity: "Trumbull"})
db.stores.insert({storeNumber: "R582",storeName: "Upper East Side",storeEnabled: true,storeState: "New York",sellEdition: false,storeCity: "New York"})
db.stores.insert({storeNumber: "R251",storeName: "Upper West Side",storeEnabled: true,storeState: "New York",sellEdition: false,storeCity: "New York"})
db.stores.insert({storeNumber: "R068",storeName: "Walt Whitman",storeEnabled: true,storeState: "New York",sellEdition: false,storeCity: "Huntington Station"})
db.stores.insert({storeNumber: "R250",storeName: "West 14th Street",storeEnabled: true,storeState: "New York",sellEdition: false,storeCity: "New York"})
db.stores.insert({storeNumber: "R594",storeName: "Williamsburg",storeEnabled: true,storeState: "New York",sellEdition: false,storeCity: "Brooklyn"})
db.stores.insert({storeNumber: "R325",storeName: "Willowbrook",storeEnabled: true,storeState: "New Jersey",sellEdition: false,storeCity: "Wayne"})
db.stores.insert({storeNumber: "R654",storeName: "World Trade Center",storeEnabled: true,storeState: "New York",sellEdition: false,storeCity: "New York"})